"""debug comments

Revision ID: 15fceca73286
Revises: fba166572d0e
Create Date: 2022-05-10 23:56:13.203818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fceca73286'
down_revision = 'fba166572d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=False))
    op.drop_constraint('comments_pitches_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'pitches_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitches_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitches_id_fkey', 'comments', 'pitches', ['pitches_id'], ['id'])
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
